fix: error TS2740: Type '{ load: Mock<any, [media: any, options: any, callback: any]>; }' is missing the following properties from type 'DefaultMediaReceiver': getStatus, pause, play, queueInsert, and 6 more.